### ISSUE TITLE
How soon will the code and model be here？

### ISSUE THREAD

**Issue by feng150416** [KimSoybean/ScratchDet#2]
How soon will the code and model be here？Thanks！

**Comment by impredicative** [comment]
Why make a duplicate issue when there already is one? It is bad practice.

**Comment by KimSoybean** [comment]
@feng150416 I think is's really an easy coding to implement a training from scratch model. ScratchDet is not for SOTA purpose. However, it is just an example to represent the benefit of training from scratch. We have implemented another codes and models on mmdetection (adding 512x512 models). I really hope that you can train some small models from scratch according to the paper, but not our codes.

**Comment by feng150416** [comment]
> @feng150416 I think is's really an easy coding to implement a training from scratch model. ScratchDet is not for SOTA purpose. However, it is just an example to represent the benefit of training from scratch. We have implemented another codes and models on mmdetection (adding 512x512 models). I really hope that you can train some small models from scratch according to the paper, but not our codes.
hi！thanks for replying.I am currently using the ssd algorithm（ssd-512 model）for my undergraduate graduation design.I have tryed to train the model from scratch with my dataset or train the model using the pretrained model，the result of detection is not good.I watch your paper，so I want to try your method.Hence I can't wait to watch your code and model。

**Comment by feng150416** [comment]
@KimSoybean   hi！thanks for replying.I am currently using the ssd algorithm（ssd-512 model）for my undergraduate graduation design.I have tryed to train the model from scratch with my dataset or train the model using the pretrained model，the result of detection is not good.I watch your paper，so I want to try your method.Hence I can't wait to watch your code and model。
